[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino

; Force utilization of the Internal oscillator (HSI) just in case the board has no valid HSE crystal
build_flags = 
    -D SYS_CLOCK=64000000L
    -D VECT_TAB_OFFSET=0x0
    -D STM32F103xB
    -D HSE_VALUE=8000000

lib_deps = thotro/DW1000@^0.9

upload_protocol = serial
upload_port = COM7
monitor_speed = 115200